services:
  nginx: 
    container_name: nginx
    build:
      context: ./requirements
      dockerfile: nginx/Dockerfile
    ports: 
      - "443:443"
    restart: on-failure
    depends_on:   
      wordpress:
        condition: service_healthy
        restart: true
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements
      dockerfile: mariadb/Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-u", "health", "-phealth_pw", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure
    networks:
      - inception
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER_ADMIN=${MYSQL_USER_ADMIN}
      - MYSQL_PASSWORD_ADMIN=${MYSQL_PASSWORD_ADMIN}
    
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements
      dockerfile: wordpress/Dockerfile
    depends_on:   
      mariadb:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9000"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - wordpress_data:/var/www/html
    restart: on-failure
    networks:
      - inception
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER_ADMIN=${MYSQL_USER_ADMIN}
      - MYSQL_PASSWORD_ADMIN=${MYSQL_PASSWORD_ADMIN}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}

networks:
  inception:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/16"

volumes:
  wordpress_data:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/abarzila/data/wordpress"

  mariadb_data:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/abarzila/data/mariadb"
